from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

# ✅ Default reports for IdeaNest
default_reports = [
    "📊 Idea Submission Report: 25 ideas submitted this month.",
    "📈 Dashboard Activity Report: 12 active users today.",
    "📉 Analytics Report: Average idea rating 4.2/5.",
    "🤝 Collaboration Report: 8 team discussions started.",
    "🔔 Notifications Report: 20 alerts sent.",
    "👥 User Growth Report: 10 new registrations this week.",
    "⚡ Performance Report: Smart Farming Dashboard growing fastest.",
    "🤖 AI Suggestions Report: 5 ideas generated by AI.",
    "🛡️ System Health Report: Uptime 99.9%.",
    "📤 Export Summary Report: 6 reports exported."
]

@csrf_exempt
def reports_view(request):
    return render(request, "reports/analytics.html", {"reports": default_reports})
